apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: zone-ingress
  namespace: zoneprinter
  annotation:
    configmanagement.gke.io/cluster-selector: cluster-selector-config
spec:
  template:
    spec:
      backend:
        serviceName: zone-mcs
        servicePort: 8080